from app.seed_data.seed_model.seed_days import seed_days
from app.seed_data.seed_model.seed_dezyderata import seed_dezyderata
from app.seed_data.seed_model.seed_departments import seed_departments
from app.seed_data.seed_model.seed_departments_for_user import seed_departments_for_user
from app.seed_data.seed_model.seed_grades import seed_grades
from app.seed_data.seed_model.seed_groups import seed_groups
from app.seed_data.seed_model.seed_roles import seed_roles
from app.seed_data.seed_model.seed_rooms import seed_rooms
from app.seed_data.seed_model.seed_semesters import seed_semesters
from app.seed_data.seed_model.seed_subjects import seed_subjects
from app.seed_data.seed_model.seed_teacher_student_profiles import seed_teacher_student_profiles
from app.seed_data.seed_model.seed_users import seed_users
