services:
  frontend:
    build:
      context: ../ZPI-Desktop-App
      dockerfile: Dockerfile
    container_name: zpi-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ZPI-Desktop-Backend
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
  seed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zpi-backend-seed
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    command: [ "python", "-m", "app.seed_data.seed_all" ]
    profiles:
      - seed
  db:
    image: postgres:16
    container_name: zpi-postgres
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
