"""user_login and delate logins

Revision ID: 3a60cf90af40
Revises: 
Create Date: 2026-03-12 23:43:56.521798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a60cf90af40'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logins_id'), table_name='logins')
    op.drop_table('logins')

    # Ręczne tworzenie typów ENUM dla PostgreSQL
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_rola') THEN
                CREATE TYPE user_rola AS ENUM ('wykladowca', 'cwiczenia', 'laboratorium', 'seminarium', 'student', 'inne');
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_dzial') THEN
                CREATE TYPE user_dzial AS ENUM ('informatyka', 'mechatronika', 'energetyka');
            END IF;
        END $$;
    """)

    op.add_column('users', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('login', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('rola', sa.Enum('WYKLADOWCA', 'CWICZENIA', 'LABORATORIUM', 'SEMINARIUM', 'STUDENT', 'INNE', name='user_rola'), nullable=False))
    op.add_column('users', sa.Column('dzial', sa.Enum('INFORMATYKA', 'MECHATRONIKA', 'ENERGETYKA', name='user_dzial'), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.drop_column('users', 'password')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'dzial')
    op.drop_column('users', 'rola')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'login')
    op.drop_column('users', 'user_id')
    op.create_table('logins',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('logins_pkey'))
    )
    op.create_index(op.f('ix_logins_id'), 'logins', ['id'], unique=False)
    # ### end Alembic commands ###
