"""add imie nazwisko plain_password to users

Revision ID: 3be3a8d2e379
Revises: b1f29f84f6aa
Create Date: 2026-03-15 10:15:37.653424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be3a8d2e379'
down_revision: Union[str, Sequence[str], None] = 'b1f29f84f6aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with server_default to handle existing rows
    op.add_column('users', sa.Column('imie', sa.String(), nullable=False, server_default=''))
    op.add_column('users', sa.Column('nazwisko', sa.String(), nullable=False, server_default=''))
    op.add_column('users', sa.Column('plain_password', sa.String(), nullable=True))
    # Remove server defaults after migration
    op.alter_column('users', 'imie', server_default=None)
    op.alter_column('users', 'nazwisko', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plain_password')
    op.drop_column('users', 'nazwisko')
    op.drop_column('users', 'imie')
    # ### end Alembic commands ###
