"""fix users.user_id autoincrement default

Revision ID: 8e9e4d7d54a1
Revises: 3a60cf90af40
Create Date: 2026-03-13 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "8e9e4d7d54a1"
down_revision: Union[str, Sequence[str], None] = "3a60cf90af40"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Ensure users.user_id is auto-generated by PostgreSQL."""
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_class
                WHERE relkind = 'S' AND relname = 'users_user_id_seq'
            ) THEN
                CREATE SEQUENCE users_user_id_seq;
            END IF;
        END $$;
        """
    )

    op.execute("ALTER SEQUENCE users_user_id_seq OWNED BY users.user_id;")
    op.execute("ALTER TABLE users ALTER COLUMN user_id SET DEFAULT nextval('users_user_id_seq');")
    op.execute(
        """
        SELECT setval(
            'users_user_id_seq',
            COALESCE((SELECT MAX(user_id) FROM users), 0) + 1,
            false
        );
        """
    )

    # If the original migration removed the old PK and did not add a new one,
    # ensure user_id becomes the primary key.
    op.execute(
        """
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conrelid = 'users'::regclass
                  AND contype = 'p'
            ) THEN
                ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    """Remove auto-generation default from users.user_id."""
    op.execute("ALTER TABLE users ALTER COLUMN user_id DROP DEFAULT;")
    op.execute("DROP SEQUENCE IF EXISTS users_user_id_seq;")
