"""add refresh token sessions table

Revision ID: 92fe86fc899d
Revises: e6f8a1b9c2d3
Create Date: 2026-03-19 19:41:03.998799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92fe86fc899d'
down_revision: Union[str, Sequence[str], None] = 'e6f8a1b9c2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_sessions_id'), 'refresh_token_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_token_sessions_jti'), 'refresh_token_sessions', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_token_sessions_user_id'), 'refresh_token_sessions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_nauczyciel_id'), table_name='nauczyciel')
    op.drop_index(op.f('ix_nauczyciel_user_id'), table_name='nauczyciel')
    op.drop_table('nauczyciel')
    op.add_column('group', sa.Column('kod', sa.String(), nullable=False))
    op.add_column('group', sa.Column('rok', sa.Integer(), nullable=False))
    op.add_column('group', sa.Column('studia', sa.String(), nullable=False))
    op.drop_column('group', 'code')
    op.drop_column('group', 'year')
    op.drop_column('group', 'studies')
    op.drop_constraint(op.f('student_nr_indeksu_key'), 'student', type_='unique')
    op.drop_constraint(op.f('student_user_id_key'), 'student', type_='unique')
    op.drop_index(op.f('ix_student_nr_indeksu'), table_name='student')
    op.create_index(op.f('ix_student_nr_indeksu'), 'student', ['nr_indeksu'], unique=True)
    op.drop_index(op.f('ix_student_user_id'), table_name='student')
    op.create_index(op.f('ix_student_user_id'), 'student', ['user_id'], unique=True)
    op.add_column('subject', sa.Column('nazwa', sa.String(), nullable=False))
    op.add_column('subject', sa.Column('rodzaj', sa.String(), nullable=False))
    op.add_column('subject', sa.Column('rodzajshow', sa.String(), nullable=True))
    op.add_column('subject', sa.Column('prop_sal', sa.String(), nullable=True))
    op.add_column('subject', sa.Column('zablokowany', sa.Boolean(), nullable=False))
    op.add_column('subject', sa.Column('periodyczny', sa.Boolean(), nullable=False))
    op.drop_column('subject', 'blocked')
    op.drop_column('subject', 'name')
    op.drop_column('subject', 'type')
    op.drop_column('subject', 'periodic')
    op.drop_column('subject', 'type_show')
    op.drop_column('subject', 'prop_room')
    op.add_column('teacher', sa.Column('tytul', sa.String(), nullable=True))
    op.drop_constraint(op.f('teacher_user_id_key'), 'teacher', type_='unique')
    op.drop_index(op.f('ix_teacher_user_id'), table_name='teacher')
    op.create_index(op.f('ix_teacher_user_id'), 'teacher', ['user_id'], unique=True)
    op.drop_column('teacher', 'title')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_login'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_login'), 'users', ['login'])
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.add_column('teacher', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_teacher_user_id'), table_name='teacher')
    op.create_index(op.f('ix_teacher_user_id'), 'teacher', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('teacher_user_id_key'), 'teacher', ['user_id'])
    op.drop_column('teacher', 'tytul')
    op.add_column('subject', sa.Column('prop_room', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('subject', sa.Column('type_show', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('subject', sa.Column('periodic', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('subject', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subject', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('subject', sa.Column('blocked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('subject', 'periodyczny')
    op.drop_column('subject', 'zablokowany')
    op.drop_column('subject', 'prop_sal')
    op.drop_column('subject', 'rodzajshow')
    op.drop_column('subject', 'rodzaj')
    op.drop_column('subject', 'nazwa')
    op.drop_index(op.f('ix_student_user_id'), table_name='student')
    op.create_index(op.f('ix_student_user_id'), 'student', ['user_id'], unique=False)
    op.drop_index(op.f('ix_student_nr_indeksu'), table_name='student')
    op.create_index(op.f('ix_student_nr_indeksu'), 'student', ['nr_indeksu'], unique=False)
    op.create_unique_constraint(op.f('student_user_id_key'), 'student', ['user_id'])
    op.create_unique_constraint(op.f('student_nr_indeksu_key'), 'student', ['nr_indeksu'])
    op.add_column('group', sa.Column('studies', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('group', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('group', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('group', 'studia')
    op.drop_column('group', 'rok')
    op.drop_column('group', 'kod')
    op.create_table('nauczyciel',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tytul', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prop', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('nauczyciel_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('nauczyciel_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('nauczyciel_user_id_key'))
    )
    op.create_index(op.f('ix_nauczyciel_user_id'), 'nauczyciel', ['user_id'], unique=False)
    op.create_index(op.f('ix_nauczyciel_id'), 'nauczyciel', ['id'], unique=False)
    op.drop_index(op.f('ix_refresh_token_sessions_user_id'), table_name='refresh_token_sessions')
    op.drop_index(op.f('ix_refresh_token_sessions_jti'), table_name='refresh_token_sessions')
    op.drop_index(op.f('ix_refresh_token_sessions_id'), table_name='refresh_token_sessions')
    op.drop_table('refresh_token_sessions')
    # ### end Alembic commands ###
