"""add message e2ee fields

Revision ID: 9ef882f787ab
Revises: f67529c21069
Create Date: 2026-03-27 12:44:43.526946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef882f787ab'
down_revision: Union[str, Sequence[str], None] = 'f67529c21069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('ciphertext', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('iv', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('wrapped_key', sa.String(), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('messages', 'wrapped_key')
    op.drop_column('messages', 'iv')
    op.drop_column('messages', 'ciphertext')
    # ### end Alembic commands ###
