"""Add group_id to TeachingLoadAssignment

Revision ID: f919896e63f3
Revises: 20260531_0001
Create Date: 2026-06-07 20:16:15.452505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f919896e63f3'
down_revision: Union[str, Sequence[str], None] = '20260531_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rapla_group_to_resourc_group_id'), table_name='rapla_group_to_resourc')
    op.drop_index(op.f('ix_rapla_group_to_resourc_id'), table_name='rapla_group_to_resourc')
    op.drop_index(op.f('ix_rapla_group_to_resourc_rapla_resourc_id'), table_name='rapla_group_to_resourc')
    op.drop_table('rapla_group_to_resourc')
    op.drop_index(op.f('ix_lesson_for_group_group_id'), table_name='lesson_for_group')
    op.drop_index(op.f('ix_lesson_for_group_id'), table_name='lesson_for_group')
    op.drop_index(op.f('ix_lesson_for_group_lesson_id'), table_name='lesson_for_group')
    op.drop_table('lesson_for_group')
    op.drop_index(op.f('ix_field_of_study_for_group_field_of_study_id'), table_name='field_of_study_for_group')
    op.drop_index(op.f('ix_field_of_study_for_group_group_id'), table_name='field_of_study_for_group')
    op.drop_index(op.f('ix_field_of_study_for_group_id'), table_name='field_of_study_for_group')
    op.drop_table('field_of_study_for_group')
    op.add_column('teaching_load_assignments', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_teaching_load_assignments_group_id'), 'teaching_load_assignments', ['group_id'], unique=False)
    op.create_foreign_key(None, 'teaching_load_assignments', 'group', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teaching_load_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_teaching_load_assignments_group_id'), table_name='teaching_load_assignments')
    op.drop_column('teaching_load_assignments', 'group_id')
    op.create_table('field_of_study_for_group',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('field_of_study_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['field_of_study_id'], ['field_of_study.id'], name=op.f('field_of_study_for_group_field_of_study_id_fkey')),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('field_of_study_for_group_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('field_of_study_for_group_pkey')),
    sa.UniqueConstraint('field_of_study_id', 'group_id', name=op.f('uq_field_of_study_for_group'))
    )
    op.create_index(op.f('ix_field_of_study_for_group_id'), 'field_of_study_for_group', ['id'], unique=False)
    op.create_index(op.f('ix_field_of_study_for_group_group_id'), 'field_of_study_for_group', ['group_id'], unique=False)
    op.create_index(op.f('ix_field_of_study_for_group_field_of_study_id'), 'field_of_study_for_group', ['field_of_study_id'], unique=False)
    op.create_table('lesson_for_group',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('lesson_for_group_group_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('lesson_for_group_lesson_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lesson_for_group_pkey')),
    sa.UniqueConstraint('lesson_id', 'group_id', name=op.f('uq_lesson_for_group'))
    )
    op.create_index(op.f('ix_lesson_for_group_lesson_id'), 'lesson_for_group', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_for_group_id'), 'lesson_for_group', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_for_group_group_id'), 'lesson_for_group', ['group_id'], unique=False)
    op.create_table('rapla_group_to_resourc',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rapla_resourc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('rapla_group_to_resourc_group_id_fkey')),
    sa.ForeignKeyConstraint(['rapla_resourc_id'], ['rapla_resourc.id'], name=op.f('rapla_group_to_resourc_rapla_resourc_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rapla_group_to_resourc_pkey')),
    sa.UniqueConstraint('group_id', 'rapla_resourc_id', name=op.f('uq_rapla_group_to_resourc'))
    )
    op.create_index(op.f('ix_rapla_group_to_resourc_rapla_resourc_id'), 'rapla_group_to_resourc', ['rapla_resourc_id'], unique=False)
    op.create_index(op.f('ix_rapla_group_to_resourc_id'), 'rapla_group_to_resourc', ['id'], unique=False)
    op.create_index(op.f('ix_rapla_group_to_resourc_group_id'), 'rapla_group_to_resourc', ['group_id'], unique=False)
    # ### end Alembic commands ###
